networks:
  pekko-net:
    driver: bridge

services:
  node1:
    build: .
    hostname: node1
    networks:
      - pekko-net
    ports:
      - "8081:8080"
    environment:
      PEKKO_HOSTNAME: node1
      JAVA_TOOL_OPTIONS: -Dconfig.resource=application-docker.conf

  node2:
    build: .
    hostname: node2
    networks:
      - pekko-net
    ports:
      - "8082:8080"
    environment:
      PEKKO_HOSTNAME: node2
      JAVA_TOOL_OPTIONS: -Dconfig.resource=application-docker.conf
    depends_on:
      - node1

  node3:
    build: .
    hostname: node3
    networks:
      - pekko-net
    ports:
      - "8083:8080"
    environment:
      PEKKO_HOSTNAME: node3
      JAVA_TOOL_OPTIONS: -Dconfig.resource=application-docker.conf
    depends_on:
      - node1
