pekko {
  actor {
    provider = cluster
    allow-java-serialization = off
    serialization-bindings {
      "ee.takahiro.pekkodemo.actor.VoiceSessionSerializable" = jackson-json
    }
  }
  remote {
    artery {
      canonical {
        hostname = "127.0.0.1"
        port = 25520
      }
    }
  }
  cluster {
    seed-nodes = ["pekko://VoiceSessionSystem@127.0.0.1:25520"]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }
  persistence {
    journal.plugin = "jdbc-journal"
    snapshot-store.plugin = "jdbc-snapshot-store"
  }
}

jdbc-journal {
  slick = ${slick}
}

jdbc-snapshot-store {
  slick = ${slick}
}

jdbc-read-journal {
  slick = ${slick}
}

slick {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    url = "jdbc:postgresql://localhost:5432/pekko"
    user = "pekko"
    password = "pekko"
    driver = "org.postgresql.Driver"
  }
}
