include "application"

pekko.use-cluster-bootstrap = true

pekko.remote.artery.canonical {
  hostname = ${PEKKO_HOSTNAME}
  port = 25520
}

pekko.cluster.seed-nodes = []

pekko.management {
  http {
    hostname = ${PEKKO_HOSTNAME}
    bind-hostname = "0.0.0.0"
    port = 8558
  }
  cluster.bootstrap {
    contact-point-discovery {
      discovery-method = kubernetes-api
      service-name = "pekko-demo"
      port-name = "management"
    }
  }
}

pekko.discovery.method = kubernetes-api
