spring:
  application:
    name: pekko-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/pekko
    username: pekko
    password: pekko
    driver-class-name: org.postgresql.Driver

pekko:
  actor:
    provider: cluster
  remote:
    artery:
      canonical:
        hostname: "127.0.0.1"
        port: 25520
  cluster:
    seed-nodes:
      - "pekko://VoiceSessionSystem@127.0.0.1:25520"
    downing-provider-class: "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
