include "application"

pekko.remote.artery.canonical.hostname = ${PEKKO_HOSTNAME}
pekko.cluster.seed-nodes = ["pekko://VoiceSessionSystem@node1:25520"]

slick.db.url = "jdbc:postgresql://postgres:5432/pekko"
